version: "3.8"
services:
  # Postgres database container
  postgres1:
    image: postgres
    container_name: postgres1
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres1
      POSTGRES_PASSWORD: postgres1
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # MySQL database container
  mysql1:
    image: mysql:latest
    container_name: mysql1
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql1
      MYSQL_DATABASE: mysql1
      MYSQL_USER: mysql1
      MYSQL_PASSWORD: mysql1
    volumes:
      - mysql-data:/var/lib/mysql

  # UI for PostgreSQL databases
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  # UI for MySQL databases
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    ports:
      - "6600:80"
    environment:
      PMA_HOST: mysql1
      PMA_PORT: 3306
      PMA_USER: mysql1
      PMA_PASSWORD: mysql1

volumes:
  pgadmin-data:
  mysql-data:
  postgres-data:
